-- V1: Create booking service tables
--
-- Flyway naming convention: V{version}__{description}.sql
-- The double underscore __ is mandatory.
-- Once applied, this script is NEVER re-run (Flyway records it in flyway_schema_history).
-- To change the schema later, create V2__..., V3__... etc.

CREATE TABLE IF NOT EXISTS trips (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    traveler_id     UUID            NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    description     VARCHAR(500),
    destination     VARCHAR(255)    NOT NULL,
    start_date      DATE,
    end_date        DATE,
    status          VARCHAR(20)     NOT NULL DEFAULT 'PLANNED',
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_trip_traveler_id ON trips(traveler_id);
CREATE INDEX IF NOT EXISTS idx_trip_status ON trips(status);

COMMENT ON TABLE trips IS 'Corporate travel trips grouping one or more bookings';
COMMENT ON COLUMN trips.id IS 'UUID primary key, generated by PostgreSQL';
COMMENT ON COLUMN trips.traveler_id IS 'References the traveler in the traveler-service';

CREATE TABLE IF NOT EXISTS bookings (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id             UUID            NOT NULL REFERENCES trips(id),
    traveler_id         UUID            NOT NULL,
    booking_reference   VARCHAR(20)     NOT NULL UNIQUE,
    status              VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    total_amount        DECIMAL(19,4),
    currency            VARCHAR(3)      NOT NULL DEFAULT 'GBP',
    trace_id            VARCHAR(64),
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_booking_traveler_id ON bookings(traveler_id);
CREATE INDEX IF NOT EXISTS idx_booking_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_booking_reference ON bookings(booking_reference);
CREATE INDEX IF NOT EXISTS idx_booking_trip_id ON bookings(trip_id);

COMMENT ON TABLE bookings IS 'Individual supplier bookings (flights, hotels, cars) within a trip';
COMMENT ON COLUMN bookings.booking_reference IS 'Human-readable reference e.g. TC-AB123456';
COMMENT ON COLUMN bookings.trace_id IS 'Distributed tracing ID for correlating logs across services';

CREATE TABLE IF NOT EXISTS booking_items (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id      UUID            NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    item_type       VARCHAR(20)     NOT NULL,
    supplier_code   VARCHAR(50),
    origin          VARCHAR(10),
    destination     VARCHAR(10),
    departure_date  DATE,
    return_date     DATE,
    passengers      INTEGER         DEFAULT 1,
    price_per_unit  DECIMAL(19,4),
    quantity        INTEGER         DEFAULT 1,
    currency        VARCHAR(3)      DEFAULT 'GBP'
);

CREATE INDEX IF NOT EXISTS idx_booking_item_booking_id ON booking_items(booking_id);

COMMENT ON TABLE booking_items IS 'Line items within a booking (e.g. individual flight segments or hotel nights)';
