-- V1: Create travelers table
--
-- Flyway naming convention: V{version}__{description}.sql
-- The double underscore __ is mandatory.
-- Once applied, this script is NEVER re-run (Flyway records it in flyway_schema_history).
-- To change the schema later, create V2__..., V3__... etc.

CREATE TABLE IF NOT EXISTS travelers (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name      VARCHAR(100)    NOT NULL,
    last_name       VARCHAR(100)    NOT NULL,
    email           VARCHAR(255)    NOT NULL,
    phone           VARCHAR(30),
    date_of_birth   DATE,
    nationality     VARCHAR(100),
    passport_number VARCHAR(50),
    passport_expiry DATE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP
);

-- Email uniqueness enforced at DB level (belt-and-suspenders alongside service-layer check)
ALTER TABLE travelers
    ADD CONSTRAINT uq_traveler_email UNIQUE (email);

-- Index for email lookups (used by findByEmail)
CREATE INDEX IF NOT EXISTS idx_traveler_email
    ON travelers (email);

-- Index for name searches (used by searchByLastName)
CREATE INDEX IF NOT EXISTS idx_traveler_last_name
    ON travelers (last_name);

-- Comment for schema documentation
COMMENT ON TABLE travelers IS 'Corporate traveler profiles';
COMMENT ON COLUMN travelers.id IS 'UUID primary key, generated by PostgreSQL';
COMMENT ON COLUMN travelers.email IS 'Business email, unique across all travelers';
