server:
  port: 9001

spring:
  application:
    name: flight-supplier-mock

logging:
  level:
    com.travelconnect: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [${spring.application.name}] %logger{36} - %msg%n"
